spring:
  application:
    name: FOUNDATION-SERVICE
  r2dbc:
    url: ${R2DBC_DATABASE_URL}
    username: ${R2DBC_DATABASE_USERNAME}
    password: ${R2DBC_DATABASE_PASSWORD}
    properties:
      sslMode: REQUIRE
    pool:
      enabled: true
      initialSize: 2
      maxSize: 2

server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://placeur-service-registry.herokuapp.com/eureka
  instance:
    hostname: 172.17.75.166
